// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface CheckGameResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.CheckGameResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gravi.interview.GameResult gameResult = 1;</code>
   * @return The enum numeric value on the wire for gameResult.
   */
  int getGameResultValue();
  /**
   * <code>.gravi.interview.GameResult gameResult = 1;</code>
   * @return The gameResult.
   */
  com.gravitysketch.interview.GameResult getGameResult();
}
