// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf enum {@code gravi.interview.GameResult}
 */
public enum GameResult
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WaitMoreJoin = 0;</code>
   */
  WaitMoreJoin(0),
  /**
   * <code>Ongoing = 1;</code>
   */
  Ongoing(1),
  /**
   * <code>Win = 2;</code>
   */
  Win(2),
  /**
   * <code>Draw = 3;</code>
   */
  Draw(3),
  /**
   * <code>Lose = 4;</code>
   */
  Lose(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>WaitMoreJoin = 0;</code>
   */
  public static final int WaitMoreJoin_VALUE = 0;
  /**
   * <code>Ongoing = 1;</code>
   */
  public static final int Ongoing_VALUE = 1;
  /**
   * <code>Win = 2;</code>
   */
  public static final int Win_VALUE = 2;
  /**
   * <code>Draw = 3;</code>
   */
  public static final int Draw_VALUE = 3;
  /**
   * <code>Lose = 4;</code>
   */
  public static final int Lose_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameResult valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GameResult forNumber(int value) {
    switch (value) {
      case 0: return WaitMoreJoin;
      case 1: return Ongoing;
      case 2: return Win;
      case 3: return Draw;
      case 4: return Lose;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameResult>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameResult> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameResult>() {
          public GameResult findValueByNumber(int number) {
            return GameResult.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.getDescriptor().getEnumTypes().get(4);
  }

  private static final GameResult[] VALUES = values();

  public static GameResult valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GameResult(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gravi.interview.GameResult)
}

