// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface HellowWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.HellowWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string returnedMessage = 1;</code>
   * @return The returnedMessage.
   */
  java.lang.String getReturnedMessage();
  /**
   * <code>string returnedMessage = 1;</code>
   * @return The bytes for returnedMessage.
   */
  com.google.protobuf.ByteString
      getReturnedMessageBytes();
}
