// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface HelloWorldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.HelloWorldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greatingMessage = 1;</code>
   * @return The greatingMessage.
   */
  java.lang.String getGreatingMessage();
  /**
   * <code>string greatingMessage = 1;</code>
   * @return The bytes for greatingMessage.
   */
  com.google.protobuf.ByteString
      getGreatingMessageBytes();
}
