// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf enum {@code gravi.interview.JoinResult}
 */
public enum JoinResult
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JoinSuccess = 0;</code>
   */
  JoinSuccess(0),
  /**
   * <code>NoGame = 1;</code>
   */
  NoGame(1),
  /**
   * <code>GameFinished = 2;</code>
   */
  GameFinished(2),
  /**
   * <code>GameIsFull = 3;</code>
   */
  GameIsFull(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JoinSuccess = 0;</code>
   */
  public static final int JoinSuccess_VALUE = 0;
  /**
   * <code>NoGame = 1;</code>
   */
  public static final int NoGame_VALUE = 1;
  /**
   * <code>GameFinished = 2;</code>
   */
  public static final int GameFinished_VALUE = 2;
  /**
   * <code>GameIsFull = 3;</code>
   */
  public static final int GameIsFull_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JoinResult valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JoinResult forNumber(int value) {
    switch (value) {
      case 0: return JoinSuccess;
      case 1: return NoGame;
      case 2: return GameFinished;
      case 3: return GameIsFull;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JoinResult>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JoinResult> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JoinResult>() {
          public JoinResult findValueByNumber(int number) {
            return JoinResult.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.getDescriptor().getEnumTypes().get(2);
  }

  private static final JoinResult[] VALUES = values();

  public static JoinResult valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JoinResult(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gravi.interview.JoinResult)
}

