// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface JoinGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.JoinGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gravi.interview.JoinGameResponse.JoinGameResponseCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.gravi.interview.JoinGameResponse.JoinGameResponseCode code = 1;</code>
   * @return The code.
   */
  com.gravitysketch.interview.JoinGameResponse.JoinGameResponseCode getCode();
}
