// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface JoinGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.JoinGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gravi.interview.JoinResult result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.gravi.interview.JoinResult result = 1;</code>
   * @return The result.
   */
  com.gravitysketch.interview.JoinResult getResult();
}
