// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf enum {@code gravi.interview.OccupyResult}
 */
public enum OccupyResult
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OccupySuccess = 0;</code>
   */
  OccupySuccess(0),
  /**
   * <code>HasBeenTaken = 1;</code>
   */
  HasBeenTaken(1),
  /**
   * <code>InvalidPosition = 2;</code>
   */
  InvalidPosition(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OccupySuccess = 0;</code>
   */
  public static final int OccupySuccess_VALUE = 0;
  /**
   * <code>HasBeenTaken = 1;</code>
   */
  public static final int HasBeenTaken_VALUE = 1;
  /**
   * <code>InvalidPosition = 2;</code>
   */
  public static final int InvalidPosition_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OccupyResult valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OccupyResult forNumber(int value) {
    switch (value) {
      case 0: return OccupySuccess;
      case 1: return HasBeenTaken;
      case 2: return InvalidPosition;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OccupyResult>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OccupyResult> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OccupyResult>() {
          public OccupyResult findValueByNumber(int number) {
            return OccupyResult.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.getDescriptor().getEnumTypes().get(3);
  }

  private static final OccupyResult[] VALUES = values();

  public static OccupyResult valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OccupyResult(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:gravi.interview.OccupyResult)
}

