// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface OccupyPositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.OccupyPositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gravi.interview.OccupyResult occupyResult = 1;</code>
   * @return The enum numeric value on the wire for occupyResult.
   */
  int getOccupyResultValue();
  /**
   * <code>.gravi.interview.OccupyResult occupyResult = 1;</code>
   * @return The occupyResult.
   */
  com.gravitysketch.interview.OccupyResult getOccupyResult();
}
