// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_RpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_HelloWorldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_HelloWorldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_HellowWorldResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_HellowWorldResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CreateGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CreateGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CreateGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CreateGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_JoinGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_JoinGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_JoinGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_JoinGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_TakePositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_TakePositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_TakePositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CheckGameResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CheckGameResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CheckGameResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CheckGameResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\017gravi.interview\"\374\002\n\nRpcRequ" +
      "est\022)\n\007rpcType\030\001 \001(\0162\030.gravi.interview.R" +
      "pcType\022=\n\021helloWorldRequest\030\n \001(\0132\".grav" +
      "i.interview.HelloWorldRequest\022=\n\021createG" +
      "ameRequest\030\013 \001(\0132\".gravi.interview.Creat" +
      "eGameRequest\0229\n\017joinGameRequest\030\014 \001(\0132 ." +
      "gravi.interview.JoinGameRequest\022A\n\023takeP" +
      "ositionRequest\030\r \001(\0132$.gravi.interview.T" +
      "akePositionRequest\022G\n\026checkGameResultReq" +
      "uest\030\016 \001(\0132\'.gravi.interview.CheckGameRe" +
      "sultRequest\"\212\003\n\013RpcResponse\022*\n\006status\030\001 " +
      "\001(\0162\032.gravi.interview.RpcStatus\022A\n\023hello" +
      "wWorldResponse\030\n \001(\0132$.gravi.interview.H" +
      "ellowWorldResponse\022?\n\022createGameResponse" +
      "\030\013 \001(\0132#.gravi.interview.CreateGameRespo" +
      "nse\022;\n\020joinGameResponse\030\014 \001(\0132!.gravi.in" +
      "terview.JoinGameResponse\022C\n\024takePosition" +
      "Response\030\r \001(\0132%.gravi.interview.TakePos" +
      "itionResponse\022I\n\027checkGameResultResponse" +
      "\030\016 \001(\0132(.gravi.interview.CheckGameResult" +
      "Response\",\n\021HelloWorldRequest\022\027\n\017greatin" +
      "gMessage\030\001 \001(\t\".\n\023HellowWorldResponse\022\027\n" +
      "\017returnedMessage\030\001 \001(\t\"#\n\021CreateGameRequ" +
      "est\022\016\n\006userId\030\001 \001(\t\"$\n\022CreateGameRespons" +
      "e\022\016\n\006gameId\030\001 \001(\t\"1\n\017JoinGameRequest\022\016\n\006" +
      "userId\030\001 \001(\t\022\016\n\006gameId\030\002 \001(\t\"\257\001\n\020JoinGam" +
      "eResponse\022D\n\004code\030\001 \001(\01626.gravi.intervie" +
      "w.JoinGameResponse.JoinGameResponseCode\"" +
      "U\n\024JoinGameResponseCode\022\017\n\013JoinSuccess\020\000" +
      "\022\n\n\006NoGame\020\001\022\020\n\014GameFinished\020\002\022\016\n\nGameIs" +
      "Full\020\003\"\025\n\023TakePositionRequest\"\026\n\024TakePos" +
      "itionResponse\"\030\n\026CheckGameResultRequest\"" +
      "\031\n\027CheckGameResultResponse*_\n\007RpcType\022\017\n" +
      "\013HellowWorld\020\000\022\016\n\nCreateGame\020\001\022\014\n\010JoinGa" +
      "me\020\002\022\020\n\014TakePosition\020\003\022\023\n\017CheckGameResul" +
      "t\020\004*+\n\tRpcStatus\022\013\n\007NoError\020\000\022\021\n\rUnknown" +
      "Status\020\001B\037\n\033com.gravitysketch.interviewP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gravi_interview_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gravi_interview_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_RpcRequest_descriptor,
        new java.lang.String[] { "RpcType", "HelloWorldRequest", "CreateGameRequest", "JoinGameRequest", "TakePositionRequest", "CheckGameResultRequest", });
    internal_static_gravi_interview_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gravi_interview_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_RpcResponse_descriptor,
        new java.lang.String[] { "Status", "HellowWorldResponse", "CreateGameResponse", "JoinGameResponse", "TakePositionResponse", "CheckGameResultResponse", });
    internal_static_gravi_interview_HelloWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gravi_interview_HelloWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_HelloWorldRequest_descriptor,
        new java.lang.String[] { "GreatingMessage", });
    internal_static_gravi_interview_HellowWorldResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gravi_interview_HellowWorldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_HellowWorldResponse_descriptor,
        new java.lang.String[] { "ReturnedMessage", });
    internal_static_gravi_interview_CreateGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gravi_interview_CreateGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CreateGameRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_gravi_interview_CreateGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gravi_interview_CreateGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CreateGameResponse_descriptor,
        new java.lang.String[] { "GameId", });
    internal_static_gravi_interview_JoinGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gravi_interview_JoinGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_JoinGameRequest_descriptor,
        new java.lang.String[] { "UserId", "GameId", });
    internal_static_gravi_interview_JoinGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gravi_interview_JoinGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_JoinGameResponse_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_gravi_interview_TakePositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gravi_interview_TakePositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_TakePositionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_gravi_interview_TakePositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_TakePositionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_gravi_interview_CheckGameResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gravi_interview_CheckGameResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CheckGameResultRequest_descriptor,
        new java.lang.String[] { });
    internal_static_gravi_interview_CheckGameResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gravi_interview_CheckGameResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CheckGameResultResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
