// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_RpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_HelloWorldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_HelloWorldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_HellowWorldResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_HellowWorldResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CreateGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CreateGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CreateGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CreateGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_JoinGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_JoinGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_JoinGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_JoinGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_TakePositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_TakePositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_TakePositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CheckGameResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CheckGameResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gravi_interview_CheckGameResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gravi_interview_CheckGameResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\017gravi.interview\"\374\002\n\nRpcRequ" +
      "est\022)\n\007rpcType\030\001 \001(\0162\030.gravi.interview.R" +
      "pcType\022=\n\021helloWorldRequest\030\n \001(\0132\".grav" +
      "i.interview.HelloWorldRequest\022=\n\021createG" +
      "ameRequest\030\013 \001(\0132\".gravi.interview.Creat" +
      "eGameRequest\0229\n\017joinGameRequest\030\014 \001(\0132 ." +
      "gravi.interview.JoinGameRequest\022A\n\023takeP" +
      "ositionRequest\030\r \001(\0132$.gravi.interview.T" +
      "akePositionRequest\022G\n\026checkGameResultReq" +
      "uest\030\016 \001(\0132\'.gravi.interview.CheckGameRe" +
      "sultRequest\"\212\003\n\013RpcResponse\022*\n\006status\030\001 " +
      "\001(\0162\032.gravi.interview.RpcStatus\022A\n\023hello" +
      "wWorldResponse\030\n \001(\0132$.gravi.interview.H" +
      "ellowWorldResponse\022?\n\022createGameResponse" +
      "\030\013 \001(\0132#.gravi.interview.CreateGameRespo" +
      "nse\022;\n\020joinGameResponse\030\014 \001(\0132!.gravi.in" +
      "terview.JoinGameResponse\022C\n\024takePosition" +
      "Response\030\r \001(\0132%.gravi.interview.TakePos" +
      "itionResponse\022I\n\027checkGameResultResponse" +
      "\030\016 \001(\0132(.gravi.interview.CheckGameResult" +
      "Response\",\n\021HelloWorldRequest\022\027\n\017greatin" +
      "gMessage\030\001 \001(\t\".\n\023HellowWorldResponse\022\027\n" +
      "\017returnedMessage\030\001 \001(\t\"#\n\021CreateGameRequ" +
      "est\022\016\n\006userId\030\001 \001(\t\"$\n\022CreateGameRespons" +
      "e\022\016\n\006gameId\030\001 \001(\t\"1\n\017JoinGameRequest\022\016\n\006" +
      "userId\030\001 \001(\t\022\016\n\006gameId\030\002 \001(\t\"\235\001\n\020JoinGam" +
      "eResponse\022<\n\006result\030\001 \001(\0162,.gravi.interv" +
      "iew.JoinGameResponse.JoinResult\"K\n\nJoinR" +
      "esult\022\017\n\013JoinSuccess\020\000\022\n\n\006NoGame\020\001\022\020\n\014Ga" +
      "meFinished\020\002\022\016\n\nGameIsFull\020\003\";\n\023TakePosi" +
      "tionRequest\022\016\n\006userId\030\001 \001(\t\022\t\n\001x\030\002 \001(\005\022\t" +
      "\n\001y\030\003 \001(\005\"\247\001\n\024TakePositionResponse\022`\n\030ta" +
      "kePositionResponseCode\030\001 \001(\0162>.gravi.int" +
      "erview.TakePositionResponse.TakePosition" +
      "ResponseCode\"-\n\030TakePositionResponseCode" +
      "\022\021\n\rOccupySuccess\020\000\"(\n\026CheckGameResultRe" +
      "quest\022\016\n\006gameId\030\001 \001(\t\"\254\001\n\027CheckGameResul" +
      "tResponse\022G\n\ngameResult\030\001 \001(\01623.gravi.in" +
      "terview.CheckGameResultResponse.GameResu" +
      "lt\"H\n\nGameResult\022\020\n\014WaitMoreJoin\020\000\022\013\n\007On" +
      "going\020\001\022\007\n\003Win\020\002\022\010\n\004Draw\020\003\022\010\n\004Lose\020\004*_\n\007" +
      "RpcType\022\017\n\013HellowWorld\020\000\022\016\n\nCreateGame\020\001" +
      "\022\014\n\010JoinGame\020\002\022\020\n\014TakePosition\020\003\022\023\n\017Chec" +
      "kGameResult\020\004*+\n\tRpcStatus\022\013\n\007NoError\020\000\022" +
      "\021\n\rUnknownStatus\020\001B\037\n\033com.gravitysketch." +
      "interviewP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gravi_interview_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gravi_interview_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_RpcRequest_descriptor,
        new java.lang.String[] { "RpcType", "HelloWorldRequest", "CreateGameRequest", "JoinGameRequest", "TakePositionRequest", "CheckGameResultRequest", });
    internal_static_gravi_interview_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gravi_interview_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_RpcResponse_descriptor,
        new java.lang.String[] { "Status", "HellowWorldResponse", "CreateGameResponse", "JoinGameResponse", "TakePositionResponse", "CheckGameResultResponse", });
    internal_static_gravi_interview_HelloWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gravi_interview_HelloWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_HelloWorldRequest_descriptor,
        new java.lang.String[] { "GreatingMessage", });
    internal_static_gravi_interview_HellowWorldResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gravi_interview_HellowWorldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_HellowWorldResponse_descriptor,
        new java.lang.String[] { "ReturnedMessage", });
    internal_static_gravi_interview_CreateGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gravi_interview_CreateGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CreateGameRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_gravi_interview_CreateGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gravi_interview_CreateGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CreateGameResponse_descriptor,
        new java.lang.String[] { "GameId", });
    internal_static_gravi_interview_JoinGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gravi_interview_JoinGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_JoinGameRequest_descriptor,
        new java.lang.String[] { "UserId", "GameId", });
    internal_static_gravi_interview_JoinGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gravi_interview_JoinGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_JoinGameResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_gravi_interview_TakePositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gravi_interview_TakePositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_TakePositionRequest_descriptor,
        new java.lang.String[] { "UserId", "X", "Y", });
    internal_static_gravi_interview_TakePositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_TakePositionResponse_descriptor,
        new java.lang.String[] { "TakePositionResponseCode", });
    internal_static_gravi_interview_CheckGameResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gravi_interview_CheckGameResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CheckGameResultRequest_descriptor,
        new java.lang.String[] { "GameId", });
    internal_static_gravi_interview_CheckGameResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gravi_interview_CheckGameResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gravi_interview_CheckGameResultResponse_descriptor,
        new java.lang.String[] { "GameResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
