// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gravi.interview.RpcStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.gravi.interview.RpcStatus status = 1;</code>
   * @return The status.
   */
  com.gravitysketch.interview.RpcStatus getStatus();

  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   * @return Whether the hellowWorldResponse field is set.
   */
  boolean hasHellowWorldResponse();
  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   * @return The hellowWorldResponse.
   */
  com.gravitysketch.interview.HellowWorldResponse getHellowWorldResponse();
  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   */
  com.gravitysketch.interview.HellowWorldResponseOrBuilder getHellowWorldResponseOrBuilder();

  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   * @return Whether the createGameResponse field is set.
   */
  boolean hasCreateGameResponse();
  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   * @return The createGameResponse.
   */
  com.gravitysketch.interview.CreateGameResponse getCreateGameResponse();
  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   */
  com.gravitysketch.interview.CreateGameResponseOrBuilder getCreateGameResponseOrBuilder();

  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   * @return Whether the joinGameResponse field is set.
   */
  boolean hasJoinGameResponse();
  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   * @return The joinGameResponse.
   */
  com.gravitysketch.interview.JoinGameResponse getJoinGameResponse();
  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   */
  com.gravitysketch.interview.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder();

  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   * @return Whether the occupyPositionResponse field is set.
   */
  boolean hasOccupyPositionResponse();
  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   * @return The occupyPositionResponse.
   */
  com.gravitysketch.interview.OccupyPositionResponse getOccupyPositionResponse();
  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   */
  com.gravitysketch.interview.OccupyPositionResponseOrBuilder getOccupyPositionResponseOrBuilder();

  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   * @return Whether the checkGameResultResponse field is set.
   */
  boolean hasCheckGameResultResponse();
  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   * @return The checkGameResultResponse.
   */
  com.gravitysketch.interview.CheckGameResultResponse getCheckGameResultResponse();
  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   */
  com.gravitysketch.interview.CheckGameResultResponseOrBuilder getCheckGameResultResponseOrBuilder();
}
