// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf type {@code gravi.interview.RpcResponse}
 */
public  final class RpcResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gravi.interview.RpcResponse)
    RpcResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RpcResponse.newBuilder() to construct.
  private RpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcResponse() {
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RpcResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RpcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 82: {
            com.gravitysketch.interview.HellowWorldResponse.Builder subBuilder = null;
            if (hellowWorldResponse_ != null) {
              subBuilder = hellowWorldResponse_.toBuilder();
            }
            hellowWorldResponse_ = input.readMessage(com.gravitysketch.interview.HellowWorldResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hellowWorldResponse_);
              hellowWorldResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.gravitysketch.interview.CreateGameResponse.Builder subBuilder = null;
            if (createGameResponse_ != null) {
              subBuilder = createGameResponse_.toBuilder();
            }
            createGameResponse_ = input.readMessage(com.gravitysketch.interview.CreateGameResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createGameResponse_);
              createGameResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            com.gravitysketch.interview.JoinGameResponse.Builder subBuilder = null;
            if (joinGameResponse_ != null) {
              subBuilder = joinGameResponse_.toBuilder();
            }
            joinGameResponse_ = input.readMessage(com.gravitysketch.interview.JoinGameResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(joinGameResponse_);
              joinGameResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            com.gravitysketch.interview.OccupyPositionResponse.Builder subBuilder = null;
            if (occupyPositionResponse_ != null) {
              subBuilder = occupyPositionResponse_.toBuilder();
            }
            occupyPositionResponse_ = input.readMessage(com.gravitysketch.interview.OccupyPositionResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(occupyPositionResponse_);
              occupyPositionResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            com.gravitysketch.interview.CheckGameResultResponse.Builder subBuilder = null;
            if (checkGameResultResponse_ != null) {
              subBuilder = checkGameResultResponse_.toBuilder();
            }
            checkGameResultResponse_ = input.readMessage(com.gravitysketch.interview.CheckGameResultResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(checkGameResultResponse_);
              checkGameResultResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gravitysketch.interview.RpcResponse.class, com.gravitysketch.interview.RpcResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.gravi.interview.RpcStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.gravi.interview.RpcStatus status = 1;</code>
   * @return The status.
   */
  public com.gravitysketch.interview.RpcStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.gravitysketch.interview.RpcStatus result = com.gravitysketch.interview.RpcStatus.valueOf(status_);
    return result == null ? com.gravitysketch.interview.RpcStatus.UNRECOGNIZED : result;
  }

  public static final int HELLOWWORLDRESPONSE_FIELD_NUMBER = 10;
  private com.gravitysketch.interview.HellowWorldResponse hellowWorldResponse_;
  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   * @return Whether the hellowWorldResponse field is set.
   */
  public boolean hasHellowWorldResponse() {
    return hellowWorldResponse_ != null;
  }
  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   * @return The hellowWorldResponse.
   */
  public com.gravitysketch.interview.HellowWorldResponse getHellowWorldResponse() {
    return hellowWorldResponse_ == null ? com.gravitysketch.interview.HellowWorldResponse.getDefaultInstance() : hellowWorldResponse_;
  }
  /**
   * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
   */
  public com.gravitysketch.interview.HellowWorldResponseOrBuilder getHellowWorldResponseOrBuilder() {
    return getHellowWorldResponse();
  }

  public static final int CREATEGAMERESPONSE_FIELD_NUMBER = 11;
  private com.gravitysketch.interview.CreateGameResponse createGameResponse_;
  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   * @return Whether the createGameResponse field is set.
   */
  public boolean hasCreateGameResponse() {
    return createGameResponse_ != null;
  }
  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   * @return The createGameResponse.
   */
  public com.gravitysketch.interview.CreateGameResponse getCreateGameResponse() {
    return createGameResponse_ == null ? com.gravitysketch.interview.CreateGameResponse.getDefaultInstance() : createGameResponse_;
  }
  /**
   * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
   */
  public com.gravitysketch.interview.CreateGameResponseOrBuilder getCreateGameResponseOrBuilder() {
    return getCreateGameResponse();
  }

  public static final int JOINGAMERESPONSE_FIELD_NUMBER = 12;
  private com.gravitysketch.interview.JoinGameResponse joinGameResponse_;
  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   * @return Whether the joinGameResponse field is set.
   */
  public boolean hasJoinGameResponse() {
    return joinGameResponse_ != null;
  }
  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   * @return The joinGameResponse.
   */
  public com.gravitysketch.interview.JoinGameResponse getJoinGameResponse() {
    return joinGameResponse_ == null ? com.gravitysketch.interview.JoinGameResponse.getDefaultInstance() : joinGameResponse_;
  }
  /**
   * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
   */
  public com.gravitysketch.interview.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder() {
    return getJoinGameResponse();
  }

  public static final int OCCUPYPOSITIONRESPONSE_FIELD_NUMBER = 13;
  private com.gravitysketch.interview.OccupyPositionResponse occupyPositionResponse_;
  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   * @return Whether the occupyPositionResponse field is set.
   */
  public boolean hasOccupyPositionResponse() {
    return occupyPositionResponse_ != null;
  }
  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   * @return The occupyPositionResponse.
   */
  public com.gravitysketch.interview.OccupyPositionResponse getOccupyPositionResponse() {
    return occupyPositionResponse_ == null ? com.gravitysketch.interview.OccupyPositionResponse.getDefaultInstance() : occupyPositionResponse_;
  }
  /**
   * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
   */
  public com.gravitysketch.interview.OccupyPositionResponseOrBuilder getOccupyPositionResponseOrBuilder() {
    return getOccupyPositionResponse();
  }

  public static final int CHECKGAMERESULTRESPONSE_FIELD_NUMBER = 14;
  private com.gravitysketch.interview.CheckGameResultResponse checkGameResultResponse_;
  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   * @return Whether the checkGameResultResponse field is set.
   */
  public boolean hasCheckGameResultResponse() {
    return checkGameResultResponse_ != null;
  }
  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   * @return The checkGameResultResponse.
   */
  public com.gravitysketch.interview.CheckGameResultResponse getCheckGameResultResponse() {
    return checkGameResultResponse_ == null ? com.gravitysketch.interview.CheckGameResultResponse.getDefaultInstance() : checkGameResultResponse_;
  }
  /**
   * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
   */
  public com.gravitysketch.interview.CheckGameResultResponseOrBuilder getCheckGameResultResponseOrBuilder() {
    return getCheckGameResultResponse();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.gravitysketch.interview.RpcStatus.NoError.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (hellowWorldResponse_ != null) {
      output.writeMessage(10, getHellowWorldResponse());
    }
    if (createGameResponse_ != null) {
      output.writeMessage(11, getCreateGameResponse());
    }
    if (joinGameResponse_ != null) {
      output.writeMessage(12, getJoinGameResponse());
    }
    if (occupyPositionResponse_ != null) {
      output.writeMessage(13, getOccupyPositionResponse());
    }
    if (checkGameResultResponse_ != null) {
      output.writeMessage(14, getCheckGameResultResponse());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.gravitysketch.interview.RpcStatus.NoError.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (hellowWorldResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getHellowWorldResponse());
    }
    if (createGameResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCreateGameResponse());
    }
    if (joinGameResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getJoinGameResponse());
    }
    if (occupyPositionResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getOccupyPositionResponse());
    }
    if (checkGameResultResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getCheckGameResultResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gravitysketch.interview.RpcResponse)) {
      return super.equals(obj);
    }
    com.gravitysketch.interview.RpcResponse other = (com.gravitysketch.interview.RpcResponse) obj;

    if (status_ != other.status_) return false;
    if (hasHellowWorldResponse() != other.hasHellowWorldResponse()) return false;
    if (hasHellowWorldResponse()) {
      if (!getHellowWorldResponse()
          .equals(other.getHellowWorldResponse())) return false;
    }
    if (hasCreateGameResponse() != other.hasCreateGameResponse()) return false;
    if (hasCreateGameResponse()) {
      if (!getCreateGameResponse()
          .equals(other.getCreateGameResponse())) return false;
    }
    if (hasJoinGameResponse() != other.hasJoinGameResponse()) return false;
    if (hasJoinGameResponse()) {
      if (!getJoinGameResponse()
          .equals(other.getJoinGameResponse())) return false;
    }
    if (hasOccupyPositionResponse() != other.hasOccupyPositionResponse()) return false;
    if (hasOccupyPositionResponse()) {
      if (!getOccupyPositionResponse()
          .equals(other.getOccupyPositionResponse())) return false;
    }
    if (hasCheckGameResultResponse() != other.hasCheckGameResultResponse()) return false;
    if (hasCheckGameResultResponse()) {
      if (!getCheckGameResultResponse()
          .equals(other.getCheckGameResultResponse())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasHellowWorldResponse()) {
      hash = (37 * hash) + HELLOWWORLDRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getHellowWorldResponse().hashCode();
    }
    if (hasCreateGameResponse()) {
      hash = (37 * hash) + CREATEGAMERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getCreateGameResponse().hashCode();
    }
    if (hasJoinGameResponse()) {
      hash = (37 * hash) + JOINGAMERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getJoinGameResponse().hashCode();
    }
    if (hasOccupyPositionResponse()) {
      hash = (37 * hash) + OCCUPYPOSITIONRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getOccupyPositionResponse().hashCode();
    }
    if (hasCheckGameResultResponse()) {
      hash = (37 * hash) + CHECKGAMERESULTRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getCheckGameResultResponse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gravitysketch.interview.RpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gravitysketch.interview.RpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gravi.interview.RpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gravi.interview.RpcResponse)
      com.gravitysketch.interview.RpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gravitysketch.interview.RpcResponse.class, com.gravitysketch.interview.RpcResponse.Builder.class);
    }

    // Construct using com.gravitysketch.interview.RpcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (hellowWorldResponseBuilder_ == null) {
        hellowWorldResponse_ = null;
      } else {
        hellowWorldResponse_ = null;
        hellowWorldResponseBuilder_ = null;
      }
      if (createGameResponseBuilder_ == null) {
        createGameResponse_ = null;
      } else {
        createGameResponse_ = null;
        createGameResponseBuilder_ = null;
      }
      if (joinGameResponseBuilder_ == null) {
        joinGameResponse_ = null;
      } else {
        joinGameResponse_ = null;
        joinGameResponseBuilder_ = null;
      }
      if (occupyPositionResponseBuilder_ == null) {
        occupyPositionResponse_ = null;
      } else {
        occupyPositionResponse_ = null;
        occupyPositionResponseBuilder_ = null;
      }
      if (checkGameResultResponseBuilder_ == null) {
        checkGameResultResponse_ = null;
      } else {
        checkGameResultResponse_ = null;
        checkGameResultResponseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcResponse_descriptor;
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcResponse getDefaultInstanceForType() {
      return com.gravitysketch.interview.RpcResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcResponse build() {
      com.gravitysketch.interview.RpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcResponse buildPartial() {
      com.gravitysketch.interview.RpcResponse result = new com.gravitysketch.interview.RpcResponse(this);
      result.status_ = status_;
      if (hellowWorldResponseBuilder_ == null) {
        result.hellowWorldResponse_ = hellowWorldResponse_;
      } else {
        result.hellowWorldResponse_ = hellowWorldResponseBuilder_.build();
      }
      if (createGameResponseBuilder_ == null) {
        result.createGameResponse_ = createGameResponse_;
      } else {
        result.createGameResponse_ = createGameResponseBuilder_.build();
      }
      if (joinGameResponseBuilder_ == null) {
        result.joinGameResponse_ = joinGameResponse_;
      } else {
        result.joinGameResponse_ = joinGameResponseBuilder_.build();
      }
      if (occupyPositionResponseBuilder_ == null) {
        result.occupyPositionResponse_ = occupyPositionResponse_;
      } else {
        result.occupyPositionResponse_ = occupyPositionResponseBuilder_.build();
      }
      if (checkGameResultResponseBuilder_ == null) {
        result.checkGameResultResponse_ = checkGameResultResponse_;
      } else {
        result.checkGameResultResponse_ = checkGameResultResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gravitysketch.interview.RpcResponse) {
        return mergeFrom((com.gravitysketch.interview.RpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gravitysketch.interview.RpcResponse other) {
      if (other == com.gravitysketch.interview.RpcResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasHellowWorldResponse()) {
        mergeHellowWorldResponse(other.getHellowWorldResponse());
      }
      if (other.hasCreateGameResponse()) {
        mergeCreateGameResponse(other.getCreateGameResponse());
      }
      if (other.hasJoinGameResponse()) {
        mergeJoinGameResponse(other.getJoinGameResponse());
      }
      if (other.hasOccupyPositionResponse()) {
        mergeOccupyPositionResponse(other.getOccupyPositionResponse());
      }
      if (other.hasCheckGameResultResponse()) {
        mergeCheckGameResultResponse(other.getCheckGameResultResponse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gravitysketch.interview.RpcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gravitysketch.interview.RpcResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.gravi.interview.RpcStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.gravi.interview.RpcStatus status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.RpcStatus status = 1;</code>
     * @return The status.
     */
    public com.gravitysketch.interview.RpcStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.gravitysketch.interview.RpcStatus result = com.gravitysketch.interview.RpcStatus.valueOf(status_);
      return result == null ? com.gravitysketch.interview.RpcStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.gravi.interview.RpcStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.gravitysketch.interview.RpcStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.RpcStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.gravitysketch.interview.HellowWorldResponse hellowWorldResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.HellowWorldResponse, com.gravitysketch.interview.HellowWorldResponse.Builder, com.gravitysketch.interview.HellowWorldResponseOrBuilder> hellowWorldResponseBuilder_;
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     * @return Whether the hellowWorldResponse field is set.
     */
    public boolean hasHellowWorldResponse() {
      return hellowWorldResponseBuilder_ != null || hellowWorldResponse_ != null;
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     * @return The hellowWorldResponse.
     */
    public com.gravitysketch.interview.HellowWorldResponse getHellowWorldResponse() {
      if (hellowWorldResponseBuilder_ == null) {
        return hellowWorldResponse_ == null ? com.gravitysketch.interview.HellowWorldResponse.getDefaultInstance() : hellowWorldResponse_;
      } else {
        return hellowWorldResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public Builder setHellowWorldResponse(com.gravitysketch.interview.HellowWorldResponse value) {
      if (hellowWorldResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hellowWorldResponse_ = value;
        onChanged();
      } else {
        hellowWorldResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public Builder setHellowWorldResponse(
        com.gravitysketch.interview.HellowWorldResponse.Builder builderForValue) {
      if (hellowWorldResponseBuilder_ == null) {
        hellowWorldResponse_ = builderForValue.build();
        onChanged();
      } else {
        hellowWorldResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public Builder mergeHellowWorldResponse(com.gravitysketch.interview.HellowWorldResponse value) {
      if (hellowWorldResponseBuilder_ == null) {
        if (hellowWorldResponse_ != null) {
          hellowWorldResponse_ =
            com.gravitysketch.interview.HellowWorldResponse.newBuilder(hellowWorldResponse_).mergeFrom(value).buildPartial();
        } else {
          hellowWorldResponse_ = value;
        }
        onChanged();
      } else {
        hellowWorldResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public Builder clearHellowWorldResponse() {
      if (hellowWorldResponseBuilder_ == null) {
        hellowWorldResponse_ = null;
        onChanged();
      } else {
        hellowWorldResponse_ = null;
        hellowWorldResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public com.gravitysketch.interview.HellowWorldResponse.Builder getHellowWorldResponseBuilder() {
      
      onChanged();
      return getHellowWorldResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    public com.gravitysketch.interview.HellowWorldResponseOrBuilder getHellowWorldResponseOrBuilder() {
      if (hellowWorldResponseBuilder_ != null) {
        return hellowWorldResponseBuilder_.getMessageOrBuilder();
      } else {
        return hellowWorldResponse_ == null ?
            com.gravitysketch.interview.HellowWorldResponse.getDefaultInstance() : hellowWorldResponse_;
      }
    }
    /**
     * <code>.gravi.interview.HellowWorldResponse hellowWorldResponse = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.HellowWorldResponse, com.gravitysketch.interview.HellowWorldResponse.Builder, com.gravitysketch.interview.HellowWorldResponseOrBuilder> 
        getHellowWorldResponseFieldBuilder() {
      if (hellowWorldResponseBuilder_ == null) {
        hellowWorldResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.HellowWorldResponse, com.gravitysketch.interview.HellowWorldResponse.Builder, com.gravitysketch.interview.HellowWorldResponseOrBuilder>(
                getHellowWorldResponse(),
                getParentForChildren(),
                isClean());
        hellowWorldResponse_ = null;
      }
      return hellowWorldResponseBuilder_;
    }

    private com.gravitysketch.interview.CreateGameResponse createGameResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CreateGameResponse, com.gravitysketch.interview.CreateGameResponse.Builder, com.gravitysketch.interview.CreateGameResponseOrBuilder> createGameResponseBuilder_;
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     * @return Whether the createGameResponse field is set.
     */
    public boolean hasCreateGameResponse() {
      return createGameResponseBuilder_ != null || createGameResponse_ != null;
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     * @return The createGameResponse.
     */
    public com.gravitysketch.interview.CreateGameResponse getCreateGameResponse() {
      if (createGameResponseBuilder_ == null) {
        return createGameResponse_ == null ? com.gravitysketch.interview.CreateGameResponse.getDefaultInstance() : createGameResponse_;
      } else {
        return createGameResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public Builder setCreateGameResponse(com.gravitysketch.interview.CreateGameResponse value) {
      if (createGameResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createGameResponse_ = value;
        onChanged();
      } else {
        createGameResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public Builder setCreateGameResponse(
        com.gravitysketch.interview.CreateGameResponse.Builder builderForValue) {
      if (createGameResponseBuilder_ == null) {
        createGameResponse_ = builderForValue.build();
        onChanged();
      } else {
        createGameResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public Builder mergeCreateGameResponse(com.gravitysketch.interview.CreateGameResponse value) {
      if (createGameResponseBuilder_ == null) {
        if (createGameResponse_ != null) {
          createGameResponse_ =
            com.gravitysketch.interview.CreateGameResponse.newBuilder(createGameResponse_).mergeFrom(value).buildPartial();
        } else {
          createGameResponse_ = value;
        }
        onChanged();
      } else {
        createGameResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public Builder clearCreateGameResponse() {
      if (createGameResponseBuilder_ == null) {
        createGameResponse_ = null;
        onChanged();
      } else {
        createGameResponse_ = null;
        createGameResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public com.gravitysketch.interview.CreateGameResponse.Builder getCreateGameResponseBuilder() {
      
      onChanged();
      return getCreateGameResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    public com.gravitysketch.interview.CreateGameResponseOrBuilder getCreateGameResponseOrBuilder() {
      if (createGameResponseBuilder_ != null) {
        return createGameResponseBuilder_.getMessageOrBuilder();
      } else {
        return createGameResponse_ == null ?
            com.gravitysketch.interview.CreateGameResponse.getDefaultInstance() : createGameResponse_;
      }
    }
    /**
     * <code>.gravi.interview.CreateGameResponse createGameResponse = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CreateGameResponse, com.gravitysketch.interview.CreateGameResponse.Builder, com.gravitysketch.interview.CreateGameResponseOrBuilder> 
        getCreateGameResponseFieldBuilder() {
      if (createGameResponseBuilder_ == null) {
        createGameResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.CreateGameResponse, com.gravitysketch.interview.CreateGameResponse.Builder, com.gravitysketch.interview.CreateGameResponseOrBuilder>(
                getCreateGameResponse(),
                getParentForChildren(),
                isClean());
        createGameResponse_ = null;
      }
      return createGameResponseBuilder_;
    }

    private com.gravitysketch.interview.JoinGameResponse joinGameResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.JoinGameResponse, com.gravitysketch.interview.JoinGameResponse.Builder, com.gravitysketch.interview.JoinGameResponseOrBuilder> joinGameResponseBuilder_;
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     * @return Whether the joinGameResponse field is set.
     */
    public boolean hasJoinGameResponse() {
      return joinGameResponseBuilder_ != null || joinGameResponse_ != null;
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     * @return The joinGameResponse.
     */
    public com.gravitysketch.interview.JoinGameResponse getJoinGameResponse() {
      if (joinGameResponseBuilder_ == null) {
        return joinGameResponse_ == null ? com.gravitysketch.interview.JoinGameResponse.getDefaultInstance() : joinGameResponse_;
      } else {
        return joinGameResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public Builder setJoinGameResponse(com.gravitysketch.interview.JoinGameResponse value) {
      if (joinGameResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        joinGameResponse_ = value;
        onChanged();
      } else {
        joinGameResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public Builder setJoinGameResponse(
        com.gravitysketch.interview.JoinGameResponse.Builder builderForValue) {
      if (joinGameResponseBuilder_ == null) {
        joinGameResponse_ = builderForValue.build();
        onChanged();
      } else {
        joinGameResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public Builder mergeJoinGameResponse(com.gravitysketch.interview.JoinGameResponse value) {
      if (joinGameResponseBuilder_ == null) {
        if (joinGameResponse_ != null) {
          joinGameResponse_ =
            com.gravitysketch.interview.JoinGameResponse.newBuilder(joinGameResponse_).mergeFrom(value).buildPartial();
        } else {
          joinGameResponse_ = value;
        }
        onChanged();
      } else {
        joinGameResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public Builder clearJoinGameResponse() {
      if (joinGameResponseBuilder_ == null) {
        joinGameResponse_ = null;
        onChanged();
      } else {
        joinGameResponse_ = null;
        joinGameResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public com.gravitysketch.interview.JoinGameResponse.Builder getJoinGameResponseBuilder() {
      
      onChanged();
      return getJoinGameResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    public com.gravitysketch.interview.JoinGameResponseOrBuilder getJoinGameResponseOrBuilder() {
      if (joinGameResponseBuilder_ != null) {
        return joinGameResponseBuilder_.getMessageOrBuilder();
      } else {
        return joinGameResponse_ == null ?
            com.gravitysketch.interview.JoinGameResponse.getDefaultInstance() : joinGameResponse_;
      }
    }
    /**
     * <code>.gravi.interview.JoinGameResponse joinGameResponse = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.JoinGameResponse, com.gravitysketch.interview.JoinGameResponse.Builder, com.gravitysketch.interview.JoinGameResponseOrBuilder> 
        getJoinGameResponseFieldBuilder() {
      if (joinGameResponseBuilder_ == null) {
        joinGameResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.JoinGameResponse, com.gravitysketch.interview.JoinGameResponse.Builder, com.gravitysketch.interview.JoinGameResponseOrBuilder>(
                getJoinGameResponse(),
                getParentForChildren(),
                isClean());
        joinGameResponse_ = null;
      }
      return joinGameResponseBuilder_;
    }

    private com.gravitysketch.interview.OccupyPositionResponse occupyPositionResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.OccupyPositionResponse, com.gravitysketch.interview.OccupyPositionResponse.Builder, com.gravitysketch.interview.OccupyPositionResponseOrBuilder> occupyPositionResponseBuilder_;
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     * @return Whether the occupyPositionResponse field is set.
     */
    public boolean hasOccupyPositionResponse() {
      return occupyPositionResponseBuilder_ != null || occupyPositionResponse_ != null;
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     * @return The occupyPositionResponse.
     */
    public com.gravitysketch.interview.OccupyPositionResponse getOccupyPositionResponse() {
      if (occupyPositionResponseBuilder_ == null) {
        return occupyPositionResponse_ == null ? com.gravitysketch.interview.OccupyPositionResponse.getDefaultInstance() : occupyPositionResponse_;
      } else {
        return occupyPositionResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public Builder setOccupyPositionResponse(com.gravitysketch.interview.OccupyPositionResponse value) {
      if (occupyPositionResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        occupyPositionResponse_ = value;
        onChanged();
      } else {
        occupyPositionResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public Builder setOccupyPositionResponse(
        com.gravitysketch.interview.OccupyPositionResponse.Builder builderForValue) {
      if (occupyPositionResponseBuilder_ == null) {
        occupyPositionResponse_ = builderForValue.build();
        onChanged();
      } else {
        occupyPositionResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public Builder mergeOccupyPositionResponse(com.gravitysketch.interview.OccupyPositionResponse value) {
      if (occupyPositionResponseBuilder_ == null) {
        if (occupyPositionResponse_ != null) {
          occupyPositionResponse_ =
            com.gravitysketch.interview.OccupyPositionResponse.newBuilder(occupyPositionResponse_).mergeFrom(value).buildPartial();
        } else {
          occupyPositionResponse_ = value;
        }
        onChanged();
      } else {
        occupyPositionResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public Builder clearOccupyPositionResponse() {
      if (occupyPositionResponseBuilder_ == null) {
        occupyPositionResponse_ = null;
        onChanged();
      } else {
        occupyPositionResponse_ = null;
        occupyPositionResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public com.gravitysketch.interview.OccupyPositionResponse.Builder getOccupyPositionResponseBuilder() {
      
      onChanged();
      return getOccupyPositionResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    public com.gravitysketch.interview.OccupyPositionResponseOrBuilder getOccupyPositionResponseOrBuilder() {
      if (occupyPositionResponseBuilder_ != null) {
        return occupyPositionResponseBuilder_.getMessageOrBuilder();
      } else {
        return occupyPositionResponse_ == null ?
            com.gravitysketch.interview.OccupyPositionResponse.getDefaultInstance() : occupyPositionResponse_;
      }
    }
    /**
     * <code>.gravi.interview.OccupyPositionResponse occupyPositionResponse = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.OccupyPositionResponse, com.gravitysketch.interview.OccupyPositionResponse.Builder, com.gravitysketch.interview.OccupyPositionResponseOrBuilder> 
        getOccupyPositionResponseFieldBuilder() {
      if (occupyPositionResponseBuilder_ == null) {
        occupyPositionResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.OccupyPositionResponse, com.gravitysketch.interview.OccupyPositionResponse.Builder, com.gravitysketch.interview.OccupyPositionResponseOrBuilder>(
                getOccupyPositionResponse(),
                getParentForChildren(),
                isClean());
        occupyPositionResponse_ = null;
      }
      return occupyPositionResponseBuilder_;
    }

    private com.gravitysketch.interview.CheckGameResultResponse checkGameResultResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CheckGameResultResponse, com.gravitysketch.interview.CheckGameResultResponse.Builder, com.gravitysketch.interview.CheckGameResultResponseOrBuilder> checkGameResultResponseBuilder_;
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     * @return Whether the checkGameResultResponse field is set.
     */
    public boolean hasCheckGameResultResponse() {
      return checkGameResultResponseBuilder_ != null || checkGameResultResponse_ != null;
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     * @return The checkGameResultResponse.
     */
    public com.gravitysketch.interview.CheckGameResultResponse getCheckGameResultResponse() {
      if (checkGameResultResponseBuilder_ == null) {
        return checkGameResultResponse_ == null ? com.gravitysketch.interview.CheckGameResultResponse.getDefaultInstance() : checkGameResultResponse_;
      } else {
        return checkGameResultResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public Builder setCheckGameResultResponse(com.gravitysketch.interview.CheckGameResultResponse value) {
      if (checkGameResultResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkGameResultResponse_ = value;
        onChanged();
      } else {
        checkGameResultResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public Builder setCheckGameResultResponse(
        com.gravitysketch.interview.CheckGameResultResponse.Builder builderForValue) {
      if (checkGameResultResponseBuilder_ == null) {
        checkGameResultResponse_ = builderForValue.build();
        onChanged();
      } else {
        checkGameResultResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public Builder mergeCheckGameResultResponse(com.gravitysketch.interview.CheckGameResultResponse value) {
      if (checkGameResultResponseBuilder_ == null) {
        if (checkGameResultResponse_ != null) {
          checkGameResultResponse_ =
            com.gravitysketch.interview.CheckGameResultResponse.newBuilder(checkGameResultResponse_).mergeFrom(value).buildPartial();
        } else {
          checkGameResultResponse_ = value;
        }
        onChanged();
      } else {
        checkGameResultResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public Builder clearCheckGameResultResponse() {
      if (checkGameResultResponseBuilder_ == null) {
        checkGameResultResponse_ = null;
        onChanged();
      } else {
        checkGameResultResponse_ = null;
        checkGameResultResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public com.gravitysketch.interview.CheckGameResultResponse.Builder getCheckGameResultResponseBuilder() {
      
      onChanged();
      return getCheckGameResultResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    public com.gravitysketch.interview.CheckGameResultResponseOrBuilder getCheckGameResultResponseOrBuilder() {
      if (checkGameResultResponseBuilder_ != null) {
        return checkGameResultResponseBuilder_.getMessageOrBuilder();
      } else {
        return checkGameResultResponse_ == null ?
            com.gravitysketch.interview.CheckGameResultResponse.getDefaultInstance() : checkGameResultResponse_;
      }
    }
    /**
     * <code>.gravi.interview.CheckGameResultResponse checkGameResultResponse = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CheckGameResultResponse, com.gravitysketch.interview.CheckGameResultResponse.Builder, com.gravitysketch.interview.CheckGameResultResponseOrBuilder> 
        getCheckGameResultResponseFieldBuilder() {
      if (checkGameResultResponseBuilder_ == null) {
        checkGameResultResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.CheckGameResultResponse, com.gravitysketch.interview.CheckGameResultResponse.Builder, com.gravitysketch.interview.CheckGameResultResponseOrBuilder>(
                getCheckGameResultResponse(),
                getParentForChildren(),
                isClean());
        checkGameResultResponse_ = null;
      }
      return checkGameResultResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gravi.interview.RpcResponse)
  }

  // @@protoc_insertion_point(class_scope:gravi.interview.RpcResponse)
  private static final com.gravitysketch.interview.RpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gravitysketch.interview.RpcResponse();
  }

  public static com.gravitysketch.interview.RpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
    @java.lang.Override
    public RpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RpcResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gravitysketch.interview.RpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

