// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf type {@code gravi.interview.RpcRequest}
 */
public  final class RpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gravi.interview.RpcRequest)
    RpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RpcRequest.newBuilder() to construct.
  private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcRequest() {
    rpcType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RpcRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RpcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            rpcType_ = rawValue;
            break;
          }
          case 82: {
            com.gravitysketch.interview.HelloWorldRequest.Builder subBuilder = null;
            if (helloWorldRequest_ != null) {
              subBuilder = helloWorldRequest_.toBuilder();
            }
            helloWorldRequest_ = input.readMessage(com.gravitysketch.interview.HelloWorldRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(helloWorldRequest_);
              helloWorldRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.gravitysketch.interview.CreateGameRequest.Builder subBuilder = null;
            if (createGameRequest_ != null) {
              subBuilder = createGameRequest_.toBuilder();
            }
            createGameRequest_ = input.readMessage(com.gravitysketch.interview.CreateGameRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createGameRequest_);
              createGameRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            com.gravitysketch.interview.JoinGameRequest.Builder subBuilder = null;
            if (joinGameRequest_ != null) {
              subBuilder = joinGameRequest_.toBuilder();
            }
            joinGameRequest_ = input.readMessage(com.gravitysketch.interview.JoinGameRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(joinGameRequest_);
              joinGameRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            com.gravitysketch.interview.OccupyPositionRequest.Builder subBuilder = null;
            if (occupyPositionRequest_ != null) {
              subBuilder = occupyPositionRequest_.toBuilder();
            }
            occupyPositionRequest_ = input.readMessage(com.gravitysketch.interview.OccupyPositionRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(occupyPositionRequest_);
              occupyPositionRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            com.gravitysketch.interview.CheckGameResultRequest.Builder subBuilder = null;
            if (checkGameResultRequest_ != null) {
              subBuilder = checkGameResultRequest_.toBuilder();
            }
            checkGameResultRequest_ = input.readMessage(com.gravitysketch.interview.CheckGameResultRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(checkGameResultRequest_);
              checkGameResultRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gravitysketch.interview.RpcRequest.class, com.gravitysketch.interview.RpcRequest.Builder.class);
  }

  public static final int RPCTYPE_FIELD_NUMBER = 1;
  private int rpcType_;
  /**
   * <code>.gravi.interview.RpcType rpcType = 1;</code>
   * @return The enum numeric value on the wire for rpcType.
   */
  public int getRpcTypeValue() {
    return rpcType_;
  }
  /**
   * <code>.gravi.interview.RpcType rpcType = 1;</code>
   * @return The rpcType.
   */
  public com.gravitysketch.interview.RpcType getRpcType() {
    @SuppressWarnings("deprecation")
    com.gravitysketch.interview.RpcType result = com.gravitysketch.interview.RpcType.valueOf(rpcType_);
    return result == null ? com.gravitysketch.interview.RpcType.UNRECOGNIZED : result;
  }

  public static final int HELLOWORLDREQUEST_FIELD_NUMBER = 10;
  private com.gravitysketch.interview.HelloWorldRequest helloWorldRequest_;
  /**
   * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
   * @return Whether the helloWorldRequest field is set.
   */
  public boolean hasHelloWorldRequest() {
    return helloWorldRequest_ != null;
  }
  /**
   * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
   * @return The helloWorldRequest.
   */
  public com.gravitysketch.interview.HelloWorldRequest getHelloWorldRequest() {
    return helloWorldRequest_ == null ? com.gravitysketch.interview.HelloWorldRequest.getDefaultInstance() : helloWorldRequest_;
  }
  /**
   * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
   */
  public com.gravitysketch.interview.HelloWorldRequestOrBuilder getHelloWorldRequestOrBuilder() {
    return getHelloWorldRequest();
  }

  public static final int CREATEGAMEREQUEST_FIELD_NUMBER = 11;
  private com.gravitysketch.interview.CreateGameRequest createGameRequest_;
  /**
   * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
   * @return Whether the createGameRequest field is set.
   */
  public boolean hasCreateGameRequest() {
    return createGameRequest_ != null;
  }
  /**
   * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
   * @return The createGameRequest.
   */
  public com.gravitysketch.interview.CreateGameRequest getCreateGameRequest() {
    return createGameRequest_ == null ? com.gravitysketch.interview.CreateGameRequest.getDefaultInstance() : createGameRequest_;
  }
  /**
   * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
   */
  public com.gravitysketch.interview.CreateGameRequestOrBuilder getCreateGameRequestOrBuilder() {
    return getCreateGameRequest();
  }

  public static final int JOINGAMEREQUEST_FIELD_NUMBER = 12;
  private com.gravitysketch.interview.JoinGameRequest joinGameRequest_;
  /**
   * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
   * @return Whether the joinGameRequest field is set.
   */
  public boolean hasJoinGameRequest() {
    return joinGameRequest_ != null;
  }
  /**
   * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
   * @return The joinGameRequest.
   */
  public com.gravitysketch.interview.JoinGameRequest getJoinGameRequest() {
    return joinGameRequest_ == null ? com.gravitysketch.interview.JoinGameRequest.getDefaultInstance() : joinGameRequest_;
  }
  /**
   * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
   */
  public com.gravitysketch.interview.JoinGameRequestOrBuilder getJoinGameRequestOrBuilder() {
    return getJoinGameRequest();
  }

  public static final int OCCUPYPOSITIONREQUEST_FIELD_NUMBER = 13;
  private com.gravitysketch.interview.OccupyPositionRequest occupyPositionRequest_;
  /**
   * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
   * @return Whether the occupyPositionRequest field is set.
   */
  public boolean hasOccupyPositionRequest() {
    return occupyPositionRequest_ != null;
  }
  /**
   * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
   * @return The occupyPositionRequest.
   */
  public com.gravitysketch.interview.OccupyPositionRequest getOccupyPositionRequest() {
    return occupyPositionRequest_ == null ? com.gravitysketch.interview.OccupyPositionRequest.getDefaultInstance() : occupyPositionRequest_;
  }
  /**
   * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
   */
  public com.gravitysketch.interview.OccupyPositionRequestOrBuilder getOccupyPositionRequestOrBuilder() {
    return getOccupyPositionRequest();
  }

  public static final int CHECKGAMERESULTREQUEST_FIELD_NUMBER = 14;
  private com.gravitysketch.interview.CheckGameResultRequest checkGameResultRequest_;
  /**
   * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
   * @return Whether the checkGameResultRequest field is set.
   */
  public boolean hasCheckGameResultRequest() {
    return checkGameResultRequest_ != null;
  }
  /**
   * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
   * @return The checkGameResultRequest.
   */
  public com.gravitysketch.interview.CheckGameResultRequest getCheckGameResultRequest() {
    return checkGameResultRequest_ == null ? com.gravitysketch.interview.CheckGameResultRequest.getDefaultInstance() : checkGameResultRequest_;
  }
  /**
   * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
   */
  public com.gravitysketch.interview.CheckGameResultRequestOrBuilder getCheckGameResultRequestOrBuilder() {
    return getCheckGameResultRequest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rpcType_ != com.gravitysketch.interview.RpcType.HellowWorld.getNumber()) {
      output.writeEnum(1, rpcType_);
    }
    if (helloWorldRequest_ != null) {
      output.writeMessage(10, getHelloWorldRequest());
    }
    if (createGameRequest_ != null) {
      output.writeMessage(11, getCreateGameRequest());
    }
    if (joinGameRequest_ != null) {
      output.writeMessage(12, getJoinGameRequest());
    }
    if (occupyPositionRequest_ != null) {
      output.writeMessage(13, getOccupyPositionRequest());
    }
    if (checkGameResultRequest_ != null) {
      output.writeMessage(14, getCheckGameResultRequest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rpcType_ != com.gravitysketch.interview.RpcType.HellowWorld.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, rpcType_);
    }
    if (helloWorldRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getHelloWorldRequest());
    }
    if (createGameRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCreateGameRequest());
    }
    if (joinGameRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getJoinGameRequest());
    }
    if (occupyPositionRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getOccupyPositionRequest());
    }
    if (checkGameResultRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getCheckGameResultRequest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gravitysketch.interview.RpcRequest)) {
      return super.equals(obj);
    }
    com.gravitysketch.interview.RpcRequest other = (com.gravitysketch.interview.RpcRequest) obj;

    if (rpcType_ != other.rpcType_) return false;
    if (hasHelloWorldRequest() != other.hasHelloWorldRequest()) return false;
    if (hasHelloWorldRequest()) {
      if (!getHelloWorldRequest()
          .equals(other.getHelloWorldRequest())) return false;
    }
    if (hasCreateGameRequest() != other.hasCreateGameRequest()) return false;
    if (hasCreateGameRequest()) {
      if (!getCreateGameRequest()
          .equals(other.getCreateGameRequest())) return false;
    }
    if (hasJoinGameRequest() != other.hasJoinGameRequest()) return false;
    if (hasJoinGameRequest()) {
      if (!getJoinGameRequest()
          .equals(other.getJoinGameRequest())) return false;
    }
    if (hasOccupyPositionRequest() != other.hasOccupyPositionRequest()) return false;
    if (hasOccupyPositionRequest()) {
      if (!getOccupyPositionRequest()
          .equals(other.getOccupyPositionRequest())) return false;
    }
    if (hasCheckGameResultRequest() != other.hasCheckGameResultRequest()) return false;
    if (hasCheckGameResultRequest()) {
      if (!getCheckGameResultRequest()
          .equals(other.getCheckGameResultRequest())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RPCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + rpcType_;
    if (hasHelloWorldRequest()) {
      hash = (37 * hash) + HELLOWORLDREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getHelloWorldRequest().hashCode();
    }
    if (hasCreateGameRequest()) {
      hash = (37 * hash) + CREATEGAMEREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getCreateGameRequest().hashCode();
    }
    if (hasJoinGameRequest()) {
      hash = (37 * hash) + JOINGAMEREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getJoinGameRequest().hashCode();
    }
    if (hasOccupyPositionRequest()) {
      hash = (37 * hash) + OCCUPYPOSITIONREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getOccupyPositionRequest().hashCode();
    }
    if (hasCheckGameResultRequest()) {
      hash = (37 * hash) + CHECKGAMERESULTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getCheckGameResultRequest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gravitysketch.interview.RpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gravitysketch.interview.RpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gravi.interview.RpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gravi.interview.RpcRequest)
      com.gravitysketch.interview.RpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gravitysketch.interview.RpcRequest.class, com.gravitysketch.interview.RpcRequest.Builder.class);
    }

    // Construct using com.gravitysketch.interview.RpcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rpcType_ = 0;

      if (helloWorldRequestBuilder_ == null) {
        helloWorldRequest_ = null;
      } else {
        helloWorldRequest_ = null;
        helloWorldRequestBuilder_ = null;
      }
      if (createGameRequestBuilder_ == null) {
        createGameRequest_ = null;
      } else {
        createGameRequest_ = null;
        createGameRequestBuilder_ = null;
      }
      if (joinGameRequestBuilder_ == null) {
        joinGameRequest_ = null;
      } else {
        joinGameRequest_ = null;
        joinGameRequestBuilder_ = null;
      }
      if (occupyPositionRequestBuilder_ == null) {
        occupyPositionRequest_ = null;
      } else {
        occupyPositionRequest_ = null;
        occupyPositionRequestBuilder_ = null;
      }
      if (checkGameResultRequestBuilder_ == null) {
        checkGameResultRequest_ = null;
      } else {
        checkGameResultRequest_ = null;
        checkGameResultRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_RpcRequest_descriptor;
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcRequest getDefaultInstanceForType() {
      return com.gravitysketch.interview.RpcRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcRequest build() {
      com.gravitysketch.interview.RpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gravitysketch.interview.RpcRequest buildPartial() {
      com.gravitysketch.interview.RpcRequest result = new com.gravitysketch.interview.RpcRequest(this);
      result.rpcType_ = rpcType_;
      if (helloWorldRequestBuilder_ == null) {
        result.helloWorldRequest_ = helloWorldRequest_;
      } else {
        result.helloWorldRequest_ = helloWorldRequestBuilder_.build();
      }
      if (createGameRequestBuilder_ == null) {
        result.createGameRequest_ = createGameRequest_;
      } else {
        result.createGameRequest_ = createGameRequestBuilder_.build();
      }
      if (joinGameRequestBuilder_ == null) {
        result.joinGameRequest_ = joinGameRequest_;
      } else {
        result.joinGameRequest_ = joinGameRequestBuilder_.build();
      }
      if (occupyPositionRequestBuilder_ == null) {
        result.occupyPositionRequest_ = occupyPositionRequest_;
      } else {
        result.occupyPositionRequest_ = occupyPositionRequestBuilder_.build();
      }
      if (checkGameResultRequestBuilder_ == null) {
        result.checkGameResultRequest_ = checkGameResultRequest_;
      } else {
        result.checkGameResultRequest_ = checkGameResultRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gravitysketch.interview.RpcRequest) {
        return mergeFrom((com.gravitysketch.interview.RpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gravitysketch.interview.RpcRequest other) {
      if (other == com.gravitysketch.interview.RpcRequest.getDefaultInstance()) return this;
      if (other.rpcType_ != 0) {
        setRpcTypeValue(other.getRpcTypeValue());
      }
      if (other.hasHelloWorldRequest()) {
        mergeHelloWorldRequest(other.getHelloWorldRequest());
      }
      if (other.hasCreateGameRequest()) {
        mergeCreateGameRequest(other.getCreateGameRequest());
      }
      if (other.hasJoinGameRequest()) {
        mergeJoinGameRequest(other.getJoinGameRequest());
      }
      if (other.hasOccupyPositionRequest()) {
        mergeOccupyPositionRequest(other.getOccupyPositionRequest());
      }
      if (other.hasCheckGameResultRequest()) {
        mergeCheckGameResultRequest(other.getCheckGameResultRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gravitysketch.interview.RpcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gravitysketch.interview.RpcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int rpcType_ = 0;
    /**
     * <code>.gravi.interview.RpcType rpcType = 1;</code>
     * @return The enum numeric value on the wire for rpcType.
     */
    public int getRpcTypeValue() {
      return rpcType_;
    }
    /**
     * <code>.gravi.interview.RpcType rpcType = 1;</code>
     * @param value The enum numeric value on the wire for rpcType to set.
     * @return This builder for chaining.
     */
    public Builder setRpcTypeValue(int value) {
      rpcType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.RpcType rpcType = 1;</code>
     * @return The rpcType.
     */
    public com.gravitysketch.interview.RpcType getRpcType() {
      @SuppressWarnings("deprecation")
      com.gravitysketch.interview.RpcType result = com.gravitysketch.interview.RpcType.valueOf(rpcType_);
      return result == null ? com.gravitysketch.interview.RpcType.UNRECOGNIZED : result;
    }
    /**
     * <code>.gravi.interview.RpcType rpcType = 1;</code>
     * @param value The rpcType to set.
     * @return This builder for chaining.
     */
    public Builder setRpcType(com.gravitysketch.interview.RpcType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      rpcType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.RpcType rpcType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRpcType() {
      
      rpcType_ = 0;
      onChanged();
      return this;
    }

    private com.gravitysketch.interview.HelloWorldRequest helloWorldRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.HelloWorldRequest, com.gravitysketch.interview.HelloWorldRequest.Builder, com.gravitysketch.interview.HelloWorldRequestOrBuilder> helloWorldRequestBuilder_;
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     * @return Whether the helloWorldRequest field is set.
     */
    public boolean hasHelloWorldRequest() {
      return helloWorldRequestBuilder_ != null || helloWorldRequest_ != null;
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     * @return The helloWorldRequest.
     */
    public com.gravitysketch.interview.HelloWorldRequest getHelloWorldRequest() {
      if (helloWorldRequestBuilder_ == null) {
        return helloWorldRequest_ == null ? com.gravitysketch.interview.HelloWorldRequest.getDefaultInstance() : helloWorldRequest_;
      } else {
        return helloWorldRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public Builder setHelloWorldRequest(com.gravitysketch.interview.HelloWorldRequest value) {
      if (helloWorldRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        helloWorldRequest_ = value;
        onChanged();
      } else {
        helloWorldRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public Builder setHelloWorldRequest(
        com.gravitysketch.interview.HelloWorldRequest.Builder builderForValue) {
      if (helloWorldRequestBuilder_ == null) {
        helloWorldRequest_ = builderForValue.build();
        onChanged();
      } else {
        helloWorldRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public Builder mergeHelloWorldRequest(com.gravitysketch.interview.HelloWorldRequest value) {
      if (helloWorldRequestBuilder_ == null) {
        if (helloWorldRequest_ != null) {
          helloWorldRequest_ =
            com.gravitysketch.interview.HelloWorldRequest.newBuilder(helloWorldRequest_).mergeFrom(value).buildPartial();
        } else {
          helloWorldRequest_ = value;
        }
        onChanged();
      } else {
        helloWorldRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public Builder clearHelloWorldRequest() {
      if (helloWorldRequestBuilder_ == null) {
        helloWorldRequest_ = null;
        onChanged();
      } else {
        helloWorldRequest_ = null;
        helloWorldRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public com.gravitysketch.interview.HelloWorldRequest.Builder getHelloWorldRequestBuilder() {
      
      onChanged();
      return getHelloWorldRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    public com.gravitysketch.interview.HelloWorldRequestOrBuilder getHelloWorldRequestOrBuilder() {
      if (helloWorldRequestBuilder_ != null) {
        return helloWorldRequestBuilder_.getMessageOrBuilder();
      } else {
        return helloWorldRequest_ == null ?
            com.gravitysketch.interview.HelloWorldRequest.getDefaultInstance() : helloWorldRequest_;
      }
    }
    /**
     * <code>.gravi.interview.HelloWorldRequest helloWorldRequest = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.HelloWorldRequest, com.gravitysketch.interview.HelloWorldRequest.Builder, com.gravitysketch.interview.HelloWorldRequestOrBuilder> 
        getHelloWorldRequestFieldBuilder() {
      if (helloWorldRequestBuilder_ == null) {
        helloWorldRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.HelloWorldRequest, com.gravitysketch.interview.HelloWorldRequest.Builder, com.gravitysketch.interview.HelloWorldRequestOrBuilder>(
                getHelloWorldRequest(),
                getParentForChildren(),
                isClean());
        helloWorldRequest_ = null;
      }
      return helloWorldRequestBuilder_;
    }

    private com.gravitysketch.interview.CreateGameRequest createGameRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CreateGameRequest, com.gravitysketch.interview.CreateGameRequest.Builder, com.gravitysketch.interview.CreateGameRequestOrBuilder> createGameRequestBuilder_;
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     * @return Whether the createGameRequest field is set.
     */
    public boolean hasCreateGameRequest() {
      return createGameRequestBuilder_ != null || createGameRequest_ != null;
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     * @return The createGameRequest.
     */
    public com.gravitysketch.interview.CreateGameRequest getCreateGameRequest() {
      if (createGameRequestBuilder_ == null) {
        return createGameRequest_ == null ? com.gravitysketch.interview.CreateGameRequest.getDefaultInstance() : createGameRequest_;
      } else {
        return createGameRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public Builder setCreateGameRequest(com.gravitysketch.interview.CreateGameRequest value) {
      if (createGameRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createGameRequest_ = value;
        onChanged();
      } else {
        createGameRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public Builder setCreateGameRequest(
        com.gravitysketch.interview.CreateGameRequest.Builder builderForValue) {
      if (createGameRequestBuilder_ == null) {
        createGameRequest_ = builderForValue.build();
        onChanged();
      } else {
        createGameRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public Builder mergeCreateGameRequest(com.gravitysketch.interview.CreateGameRequest value) {
      if (createGameRequestBuilder_ == null) {
        if (createGameRequest_ != null) {
          createGameRequest_ =
            com.gravitysketch.interview.CreateGameRequest.newBuilder(createGameRequest_).mergeFrom(value).buildPartial();
        } else {
          createGameRequest_ = value;
        }
        onChanged();
      } else {
        createGameRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public Builder clearCreateGameRequest() {
      if (createGameRequestBuilder_ == null) {
        createGameRequest_ = null;
        onChanged();
      } else {
        createGameRequest_ = null;
        createGameRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public com.gravitysketch.interview.CreateGameRequest.Builder getCreateGameRequestBuilder() {
      
      onChanged();
      return getCreateGameRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    public com.gravitysketch.interview.CreateGameRequestOrBuilder getCreateGameRequestOrBuilder() {
      if (createGameRequestBuilder_ != null) {
        return createGameRequestBuilder_.getMessageOrBuilder();
      } else {
        return createGameRequest_ == null ?
            com.gravitysketch.interview.CreateGameRequest.getDefaultInstance() : createGameRequest_;
      }
    }
    /**
     * <code>.gravi.interview.CreateGameRequest createGameRequest = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CreateGameRequest, com.gravitysketch.interview.CreateGameRequest.Builder, com.gravitysketch.interview.CreateGameRequestOrBuilder> 
        getCreateGameRequestFieldBuilder() {
      if (createGameRequestBuilder_ == null) {
        createGameRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.CreateGameRequest, com.gravitysketch.interview.CreateGameRequest.Builder, com.gravitysketch.interview.CreateGameRequestOrBuilder>(
                getCreateGameRequest(),
                getParentForChildren(),
                isClean());
        createGameRequest_ = null;
      }
      return createGameRequestBuilder_;
    }

    private com.gravitysketch.interview.JoinGameRequest joinGameRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.JoinGameRequest, com.gravitysketch.interview.JoinGameRequest.Builder, com.gravitysketch.interview.JoinGameRequestOrBuilder> joinGameRequestBuilder_;
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     * @return Whether the joinGameRequest field is set.
     */
    public boolean hasJoinGameRequest() {
      return joinGameRequestBuilder_ != null || joinGameRequest_ != null;
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     * @return The joinGameRequest.
     */
    public com.gravitysketch.interview.JoinGameRequest getJoinGameRequest() {
      if (joinGameRequestBuilder_ == null) {
        return joinGameRequest_ == null ? com.gravitysketch.interview.JoinGameRequest.getDefaultInstance() : joinGameRequest_;
      } else {
        return joinGameRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public Builder setJoinGameRequest(com.gravitysketch.interview.JoinGameRequest value) {
      if (joinGameRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        joinGameRequest_ = value;
        onChanged();
      } else {
        joinGameRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public Builder setJoinGameRequest(
        com.gravitysketch.interview.JoinGameRequest.Builder builderForValue) {
      if (joinGameRequestBuilder_ == null) {
        joinGameRequest_ = builderForValue.build();
        onChanged();
      } else {
        joinGameRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public Builder mergeJoinGameRequest(com.gravitysketch.interview.JoinGameRequest value) {
      if (joinGameRequestBuilder_ == null) {
        if (joinGameRequest_ != null) {
          joinGameRequest_ =
            com.gravitysketch.interview.JoinGameRequest.newBuilder(joinGameRequest_).mergeFrom(value).buildPartial();
        } else {
          joinGameRequest_ = value;
        }
        onChanged();
      } else {
        joinGameRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public Builder clearJoinGameRequest() {
      if (joinGameRequestBuilder_ == null) {
        joinGameRequest_ = null;
        onChanged();
      } else {
        joinGameRequest_ = null;
        joinGameRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public com.gravitysketch.interview.JoinGameRequest.Builder getJoinGameRequestBuilder() {
      
      onChanged();
      return getJoinGameRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    public com.gravitysketch.interview.JoinGameRequestOrBuilder getJoinGameRequestOrBuilder() {
      if (joinGameRequestBuilder_ != null) {
        return joinGameRequestBuilder_.getMessageOrBuilder();
      } else {
        return joinGameRequest_ == null ?
            com.gravitysketch.interview.JoinGameRequest.getDefaultInstance() : joinGameRequest_;
      }
    }
    /**
     * <code>.gravi.interview.JoinGameRequest joinGameRequest = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.JoinGameRequest, com.gravitysketch.interview.JoinGameRequest.Builder, com.gravitysketch.interview.JoinGameRequestOrBuilder> 
        getJoinGameRequestFieldBuilder() {
      if (joinGameRequestBuilder_ == null) {
        joinGameRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.JoinGameRequest, com.gravitysketch.interview.JoinGameRequest.Builder, com.gravitysketch.interview.JoinGameRequestOrBuilder>(
                getJoinGameRequest(),
                getParentForChildren(),
                isClean());
        joinGameRequest_ = null;
      }
      return joinGameRequestBuilder_;
    }

    private com.gravitysketch.interview.OccupyPositionRequest occupyPositionRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.OccupyPositionRequest, com.gravitysketch.interview.OccupyPositionRequest.Builder, com.gravitysketch.interview.OccupyPositionRequestOrBuilder> occupyPositionRequestBuilder_;
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     * @return Whether the occupyPositionRequest field is set.
     */
    public boolean hasOccupyPositionRequest() {
      return occupyPositionRequestBuilder_ != null || occupyPositionRequest_ != null;
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     * @return The occupyPositionRequest.
     */
    public com.gravitysketch.interview.OccupyPositionRequest getOccupyPositionRequest() {
      if (occupyPositionRequestBuilder_ == null) {
        return occupyPositionRequest_ == null ? com.gravitysketch.interview.OccupyPositionRequest.getDefaultInstance() : occupyPositionRequest_;
      } else {
        return occupyPositionRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public Builder setOccupyPositionRequest(com.gravitysketch.interview.OccupyPositionRequest value) {
      if (occupyPositionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        occupyPositionRequest_ = value;
        onChanged();
      } else {
        occupyPositionRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public Builder setOccupyPositionRequest(
        com.gravitysketch.interview.OccupyPositionRequest.Builder builderForValue) {
      if (occupyPositionRequestBuilder_ == null) {
        occupyPositionRequest_ = builderForValue.build();
        onChanged();
      } else {
        occupyPositionRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public Builder mergeOccupyPositionRequest(com.gravitysketch.interview.OccupyPositionRequest value) {
      if (occupyPositionRequestBuilder_ == null) {
        if (occupyPositionRequest_ != null) {
          occupyPositionRequest_ =
            com.gravitysketch.interview.OccupyPositionRequest.newBuilder(occupyPositionRequest_).mergeFrom(value).buildPartial();
        } else {
          occupyPositionRequest_ = value;
        }
        onChanged();
      } else {
        occupyPositionRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public Builder clearOccupyPositionRequest() {
      if (occupyPositionRequestBuilder_ == null) {
        occupyPositionRequest_ = null;
        onChanged();
      } else {
        occupyPositionRequest_ = null;
        occupyPositionRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public com.gravitysketch.interview.OccupyPositionRequest.Builder getOccupyPositionRequestBuilder() {
      
      onChanged();
      return getOccupyPositionRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    public com.gravitysketch.interview.OccupyPositionRequestOrBuilder getOccupyPositionRequestOrBuilder() {
      if (occupyPositionRequestBuilder_ != null) {
        return occupyPositionRequestBuilder_.getMessageOrBuilder();
      } else {
        return occupyPositionRequest_ == null ?
            com.gravitysketch.interview.OccupyPositionRequest.getDefaultInstance() : occupyPositionRequest_;
      }
    }
    /**
     * <code>.gravi.interview.OccupyPositionRequest occupyPositionRequest = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.OccupyPositionRequest, com.gravitysketch.interview.OccupyPositionRequest.Builder, com.gravitysketch.interview.OccupyPositionRequestOrBuilder> 
        getOccupyPositionRequestFieldBuilder() {
      if (occupyPositionRequestBuilder_ == null) {
        occupyPositionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.OccupyPositionRequest, com.gravitysketch.interview.OccupyPositionRequest.Builder, com.gravitysketch.interview.OccupyPositionRequestOrBuilder>(
                getOccupyPositionRequest(),
                getParentForChildren(),
                isClean());
        occupyPositionRequest_ = null;
      }
      return occupyPositionRequestBuilder_;
    }

    private com.gravitysketch.interview.CheckGameResultRequest checkGameResultRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CheckGameResultRequest, com.gravitysketch.interview.CheckGameResultRequest.Builder, com.gravitysketch.interview.CheckGameResultRequestOrBuilder> checkGameResultRequestBuilder_;
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     * @return Whether the checkGameResultRequest field is set.
     */
    public boolean hasCheckGameResultRequest() {
      return checkGameResultRequestBuilder_ != null || checkGameResultRequest_ != null;
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     * @return The checkGameResultRequest.
     */
    public com.gravitysketch.interview.CheckGameResultRequest getCheckGameResultRequest() {
      if (checkGameResultRequestBuilder_ == null) {
        return checkGameResultRequest_ == null ? com.gravitysketch.interview.CheckGameResultRequest.getDefaultInstance() : checkGameResultRequest_;
      } else {
        return checkGameResultRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public Builder setCheckGameResultRequest(com.gravitysketch.interview.CheckGameResultRequest value) {
      if (checkGameResultRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkGameResultRequest_ = value;
        onChanged();
      } else {
        checkGameResultRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public Builder setCheckGameResultRequest(
        com.gravitysketch.interview.CheckGameResultRequest.Builder builderForValue) {
      if (checkGameResultRequestBuilder_ == null) {
        checkGameResultRequest_ = builderForValue.build();
        onChanged();
      } else {
        checkGameResultRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public Builder mergeCheckGameResultRequest(com.gravitysketch.interview.CheckGameResultRequest value) {
      if (checkGameResultRequestBuilder_ == null) {
        if (checkGameResultRequest_ != null) {
          checkGameResultRequest_ =
            com.gravitysketch.interview.CheckGameResultRequest.newBuilder(checkGameResultRequest_).mergeFrom(value).buildPartial();
        } else {
          checkGameResultRequest_ = value;
        }
        onChanged();
      } else {
        checkGameResultRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public Builder clearCheckGameResultRequest() {
      if (checkGameResultRequestBuilder_ == null) {
        checkGameResultRequest_ = null;
        onChanged();
      } else {
        checkGameResultRequest_ = null;
        checkGameResultRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public com.gravitysketch.interview.CheckGameResultRequest.Builder getCheckGameResultRequestBuilder() {
      
      onChanged();
      return getCheckGameResultRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    public com.gravitysketch.interview.CheckGameResultRequestOrBuilder getCheckGameResultRequestOrBuilder() {
      if (checkGameResultRequestBuilder_ != null) {
        return checkGameResultRequestBuilder_.getMessageOrBuilder();
      } else {
        return checkGameResultRequest_ == null ?
            com.gravitysketch.interview.CheckGameResultRequest.getDefaultInstance() : checkGameResultRequest_;
      }
    }
    /**
     * <code>.gravi.interview.CheckGameResultRequest checkGameResultRequest = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gravitysketch.interview.CheckGameResultRequest, com.gravitysketch.interview.CheckGameResultRequest.Builder, com.gravitysketch.interview.CheckGameResultRequestOrBuilder> 
        getCheckGameResultRequestFieldBuilder() {
      if (checkGameResultRequestBuilder_ == null) {
        checkGameResultRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gravitysketch.interview.CheckGameResultRequest, com.gravitysketch.interview.CheckGameResultRequest.Builder, com.gravitysketch.interview.CheckGameResultRequestOrBuilder>(
                getCheckGameResultRequest(),
                getParentForChildren(),
                isClean());
        checkGameResultRequest_ = null;
      }
      return checkGameResultRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gravi.interview.RpcRequest)
  }

  // @@protoc_insertion_point(class_scope:gravi.interview.RpcRequest)
  private static final com.gravitysketch.interview.RpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gravitysketch.interview.RpcRequest();
  }

  public static com.gravitysketch.interview.RpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
    @java.lang.Override
    public RpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RpcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gravitysketch.interview.RpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

