// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

public interface TakePositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gravi.interview.TakePositionRequest)
    com.google.protobuf.MessageOrBuilder {
}
