// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.gravitysketch.interview;

/**
 * Protobuf type {@code gravi.interview.TakePositionResponse}
 */
public  final class TakePositionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gravi.interview.TakePositionResponse)
    TakePositionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TakePositionResponse.newBuilder() to construct.
  private TakePositionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TakePositionResponse() {
    takePositionResponseCode_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TakePositionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TakePositionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            takePositionResponseCode_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_TakePositionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gravitysketch.interview.TakePositionResponse.class, com.gravitysketch.interview.TakePositionResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code gravi.interview.TakePositionResponse.TakePositionResponseCode}
   */
  public enum TakePositionResponseCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OccupySuccess = 0;</code>
     */
    OccupySuccess(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OccupySuccess = 0;</code>
     */
    public static final int OccupySuccess_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TakePositionResponseCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TakePositionResponseCode forNumber(int value) {
      switch (value) {
        case 0: return OccupySuccess;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TakePositionResponseCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TakePositionResponseCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TakePositionResponseCode>() {
            public TakePositionResponseCode findValueByNumber(int number) {
              return TakePositionResponseCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gravitysketch.interview.TakePositionResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final TakePositionResponseCode[] VALUES = values();

    public static TakePositionResponseCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TakePositionResponseCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gravi.interview.TakePositionResponse.TakePositionResponseCode)
  }

  public static final int TAKEPOSITIONRESPONSECODE_FIELD_NUMBER = 1;
  private int takePositionResponseCode_;
  /**
   * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
   * @return The enum numeric value on the wire for takePositionResponseCode.
   */
  public int getTakePositionResponseCodeValue() {
    return takePositionResponseCode_;
  }
  /**
   * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
   * @return The takePositionResponseCode.
   */
  public com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode getTakePositionResponseCode() {
    @SuppressWarnings("deprecation")
    com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode result = com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.valueOf(takePositionResponseCode_);
    return result == null ? com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (takePositionResponseCode_ != com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.OccupySuccess.getNumber()) {
      output.writeEnum(1, takePositionResponseCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (takePositionResponseCode_ != com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.OccupySuccess.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, takePositionResponseCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gravitysketch.interview.TakePositionResponse)) {
      return super.equals(obj);
    }
    com.gravitysketch.interview.TakePositionResponse other = (com.gravitysketch.interview.TakePositionResponse) obj;

    if (takePositionResponseCode_ != other.takePositionResponseCode_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TAKEPOSITIONRESPONSECODE_FIELD_NUMBER;
    hash = (53 * hash) + takePositionResponseCode_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gravitysketch.interview.TakePositionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gravitysketch.interview.TakePositionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gravi.interview.TakePositionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gravi.interview.TakePositionResponse)
      com.gravitysketch.interview.TakePositionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_TakePositionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_TakePositionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gravitysketch.interview.TakePositionResponse.class, com.gravitysketch.interview.TakePositionResponse.Builder.class);
    }

    // Construct using com.gravitysketch.interview.TakePositionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      takePositionResponseCode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gravitysketch.interview.Rpc.internal_static_gravi_interview_TakePositionResponse_descriptor;
    }

    @java.lang.Override
    public com.gravitysketch.interview.TakePositionResponse getDefaultInstanceForType() {
      return com.gravitysketch.interview.TakePositionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.gravitysketch.interview.TakePositionResponse build() {
      com.gravitysketch.interview.TakePositionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gravitysketch.interview.TakePositionResponse buildPartial() {
      com.gravitysketch.interview.TakePositionResponse result = new com.gravitysketch.interview.TakePositionResponse(this);
      result.takePositionResponseCode_ = takePositionResponseCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gravitysketch.interview.TakePositionResponse) {
        return mergeFrom((com.gravitysketch.interview.TakePositionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gravitysketch.interview.TakePositionResponse other) {
      if (other == com.gravitysketch.interview.TakePositionResponse.getDefaultInstance()) return this;
      if (other.takePositionResponseCode_ != 0) {
        setTakePositionResponseCodeValue(other.getTakePositionResponseCodeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gravitysketch.interview.TakePositionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gravitysketch.interview.TakePositionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int takePositionResponseCode_ = 0;
    /**
     * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
     * @return The enum numeric value on the wire for takePositionResponseCode.
     */
    public int getTakePositionResponseCodeValue() {
      return takePositionResponseCode_;
    }
    /**
     * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
     * @param value The enum numeric value on the wire for takePositionResponseCode to set.
     * @return This builder for chaining.
     */
    public Builder setTakePositionResponseCodeValue(int value) {
      takePositionResponseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
     * @return The takePositionResponseCode.
     */
    public com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode getTakePositionResponseCode() {
      @SuppressWarnings("deprecation")
      com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode result = com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.valueOf(takePositionResponseCode_);
      return result == null ? com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
     * @param value The takePositionResponseCode to set.
     * @return This builder for chaining.
     */
    public Builder setTakePositionResponseCode(com.gravitysketch.interview.TakePositionResponse.TakePositionResponseCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      takePositionResponseCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gravi.interview.TakePositionResponse.TakePositionResponseCode takePositionResponseCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTakePositionResponseCode() {
      
      takePositionResponseCode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gravi.interview.TakePositionResponse)
  }

  // @@protoc_insertion_point(class_scope:gravi.interview.TakePositionResponse)
  private static final com.gravitysketch.interview.TakePositionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gravitysketch.interview.TakePositionResponse();
  }

  public static com.gravitysketch.interview.TakePositionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TakePositionResponse>
      PARSER = new com.google.protobuf.AbstractParser<TakePositionResponse>() {
    @java.lang.Override
    public TakePositionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TakePositionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TakePositionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TakePositionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gravitysketch.interview.TakePositionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

