name: presubmit

on:
  pull_request:
    branches:
      - master

concurrency:
  group: presubmit-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'maven'

#      - name: Cache local Maven repository
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - run: mvn clean compile
