name: presubmit

on:
  pull_request:
    branches:
      - master

concurrency:
  group: presubmit-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - run: mvn clean compile